<?php $this->assets->outputCss('headercss') ?>
<?php $this->assets->outputCss('mainpagecss') ?>
<?php $this->assets->outputCss('datepickercss') ?>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">     
      <div class="col-md-4">
        <?php echo Phalcon\Tag::linkTo(array("experience/index", "Back", "class"=>'btn btn-primary btn-large btn-success')); ?> 
      </div>
      <div class="col-md-4">
      <?php $this->flash->output(); ?>
      <form method="post" name='form' action="/eattendance/experience/create">
        <div align="center">
            <h1>Create experience</h1>
        </div>
        <form>
        <?php if($type == 1 || $type == 2) { ?>
          <div class="form-group">
          <label for="iduser" > ID User</label>                       
          <select name="iduser" class="form-control" >
          <?php foreach($user as $users) { ?>
            <option value="<?php echo $users->iduser; ?>">
            <?php echo $users->iduser.'-'.$users->username; ?>
            </option> 
          <?php } ?>                   
          </select>
          </div>
        <?php }else { ?>
          <?php echo phalcon\Tag::hiddenField(array("iduser","class"=>"form-control")); ?>
        <?php } ?>
        <div class="form-group">
        <label for="title" >Title*</label>
        <?php echo $this->tag->textField(array("title", "size" => 25 ,"required"=>'required',"class"=>"form-control","placeholder"=>"Title")) ?>
        </div>
        <div class="form-group">
        <label for="description">Description</label>
        <?php echo $this->tag->textArea(array("description", "cols" => 25, "rows" => 4,"class"=>"form-control", "placeholder"=>"Description")) ?>
        </div>
        <div class="form-group">
        <label for="from_date">From Date*</label>
        <?php echo $this->tag->textField(array("from_date","size" => 25 ,"required"=>'required',"class"=>"form-control", "placeholder"=>"From Date","data-format"=>"yyyy/mm/dd","id"=>"from")) ?>
        </div>
        <div class="form-group">
        <label for="to_date">To Date*</label>
        <?php echo $this->tag->textField(array("to_date", "size" => 25 ,"required" =>'required',"class"=>"form-control", "placeholder"=>"To Date","data-format"=>"yyyy/mm/dd","id"=>"to")) ?>
        </div>
        <div class="form-group">
        <label for="company" >Company Name*</label>
        <?php echo $this->tag->textField(array("company", "size" => 25 , 
        "required" => 'required',"class"=>"form-control", "placeholder"=>"Company Name")) ?>
        </div>
        <div class="form-group">
        <label for="company_address" >Company Address*</label>
        <?php echo $this->tag->textArea(array("company_address","cols" => 25, "rows"=>4,"required" => 'required',"class"=>"form-control", "placeholder"=>"Company Address")) ?>
        </div>
        <div class="form-group">
        <label for="company_ctc" >Company CTC(In Lakhs)*</label>
        <?php echo $this->tag->textField(array("company_ctc", "size" => 25 , 
        "required" => 'required',"class"=>"form-control", "placeholder"=>"Company CTC")) ?>
        </div>
        <div id="submit_btn">
        <button type="submit" class="btn btn-default">Save</button>
        </div>
      </form>
    </form>
   </div>              
  </div>
 </div>
</div> 
<?php $this->assets->outputJs('footerjs') ?>
<?php $this->assets->outputJs('mainpagejs') ?>
<?php $this->assets->outputJs('datepickerjs') ?>
<script type="text/javascript">
            // When the document is ready
  jQuery(document).ready(function($) {
    $('#from').datepicker({       
      format : "yyyy/mm/dd",
      autoclose: true
    })
    .on('changeDate', function(selected){
      startDate = new Date(selected.date.valueOf());
      startDate.setDate(startDate.getDate(new Date(selected.date.valueOf())));
      $('#to').datepicker('setStartDate', startDate);
    });          
    $('#to').datepicker({      
      format : "yyyy/mm/dd",         
    });       
  });
</script>  


