<?php $this->assets->outputCss('headercss') ?>
<?php $this->assets->outputCss('mainpagecss') ?>
<?php $this->assets->outputCss('datepickercss') ?>

<div class="container-fluid">
  <div class="row">     
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
      <div class="col-md-4">        
      <?php echo Phalcon\Tag::linkTo(array("education/index", "Back", "class"=>'btn btn-primary btn-large btn-success')); ?>                         
      </div>
      <div class="col-md-4">
      <?php $this->flash->output(); ?>       
      <?php echo $this->tag->form("education/save") ?>
      <div align="center">
          <h1>Edit education</h1>
      </div>
      <form>
        <div class="form-group">
        <?php echo phalcon\Tag::hiddenField(array("ideducation","class"=>"form-control" ));?>
        </div>
        <div class="form-group">
        <?php echo phalcon\Tag::hiddenField(array("iduser","class"=>"form-control"));?>
        </div>
        <div class="form-group">
        <label for="title" >Title*</label>
        <?php echo $this->tag->textField(array("title", "size" => 25 , 
        "required" => 'required',"class"=>"form-control", "placeholder"=>"Title")) ?>
        </div>
        <div class="form-group">
        <label for="description"> Description</label>
        <?php echo $this->tag->textArea(array("description", "cols" => 25,"rows" => 4,
        "class"=>"form-control","placeholder"=>"Description "))?>
        </div>
        <div class="form-group">
        <label for="from_date">From Date*</label>
        <?php echo $this->tag->textField(array("from_date", "size" => 25 , 
        "required" => 'required',"class"=>"form-control", "placeholder"=>"From Date","data-format"=>"yyyy/mm/dd","id"=>"from")) ?>
        </div>
        <div class="form-group">
        <label for="to_date">To Date*</label>
        <?php echo $this->tag->textField(array("to_date", "size" => 25 , 
        "required" => 'required',"class"=>"form-control", "placeholder"=>"To Date", "data-format"=>"yyyy/mm/dd","id"=>"to")) ?>
        </div>
        <div class="form-group">
        <label for="college" >College*</label>
        <?php echo $this->tag->textField(array("college", "size" => 25 , 
        "required" => 'required',"class"=>"form-control", "placeholder"=>"College")) ?>
        </div>
        <div class="form-group">
        <label for="grade" >Grade*</label>
        <?php echo $this->tag->textField(array("grade", "size" => 25 , 
        "required" => 'required',"class"=>"form-control", "placeholder"=>"Grade")) ?>
        </div>
        <div class="form-group">
        <label for="stream" >Stream*</label>
        <?php echo $this->tag->textField(array("stream", "size" => 25 , 
        "required" => 'required',"class"=>"form-control", "placeholder"=>"Stream")) ?>
        </div>
        <div id="submit_btn">
        <button type="submit" class="btn btn-default">Submit</button>
        </div>
        </form>
      </form>      
    </div>
  </div>
</div>
</div>

<?php $this->assets->outputJs('footerjs') ?>
<?php $this->assets->outputJs('mainpagejs') ?>
<?php $this->assets->outputJs('datepickerjs') ?>

 <script type="text/javascript">
    // When the document is ready
  jQuery(document).ready(function($) {              
   $('#from').datepicker({                     
    format : "yyyy/mm/dd",
    autoclose: true
  })
  .on('changeDate', function(selected){
    startDate = new Date(selected.date.valueOf());
    startDate.setDate(startDate.getDate(new Date(selected.date.valueOf())));
    $('#to').datepicker('setStartDate', startDate);
  });                        
  $('#to').datepicker({                    
    format : "yyyy/mm/dd",                        
  });     
});
</script>  