
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("system_meta/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("system_meta", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<div align="center">
    <h1>Edit system_meta</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="meta_name">Meta Of Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("meta_name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="meta_value">Meta Of Value</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("meta_value", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
