
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("system_meta/new", "Create system_meta")) ?>
</div>

<?php echo $this->tag->form(array("system_meta/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search system_meta</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="idsystem_meta">Idsystem Of Meta</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("idsystem_meta", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="meta_name">Meta Of Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("meta_name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="meta_value">Meta Of Value</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("meta_value", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
