 <div class="modal fade" id="addEducation" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
             <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
             <h4 class="modal-title" id="exampleModalLabel">Add Education </h4>
            </div>
            <div class="modal-body"> 
              <form method="post" name='form' id="formEducation" action="/eattendance/education/create">
              <?php $this->flash->output(); ?> 
              
              <div class="form-group">
              <?php echo phalcon\Tag::hiddenField(array("user[iduser]","class"=>"form-control")); ?>
              </div>
              <div class="form-group">
              <label for="title" >Title*</label>
              <?php echo $this->tag->textField(array("title", "size" => 25 ,"required" => 'required',"class"=>"form-control", "placeholder"=>"Title")) ?>
              </div>
              <div class="form-group">
              <label for="description">Description</label>
              <?php echo $this->tag->textArea(array("description", "cols" => 25, "rows"=> 4,"class"=>"form-control", "placeholder"=>"Description")) ?>
              </div>
              <div class="form-group">
              <label for="from_date">From Date*</label>
              <?php echo $this->tag->textField(array("from_date", "size" => 25 ,"class"=>"form-control", "placeholder"=>"From Date","data-format"=>"yyyy/mm/dd","id"=>"from1")) ?>
              </div>
              <div class="form-group">
              <label for="to_date">To Date*</label>
              <?php echo $this->tag->textField(array("to_date", "size" => 25 ,"required" =>'required',"class"=>"form-control", "placeholder"=>"To Date","data-format"=>"yyyy/mm/dd","id"=>"to1")) ?>
              </div>
              <div class="form-group">
              <label for="college" >College*</label>
              <?php echo $this->tag->textField(array("college", "size" => 25 ,"required" => 'required',"class"=>"form-control", "placeholder"=>"College Name")) ?>
              </div>
              <div class="form-group">
              <label for="grade">Grade*</label>
              <?php echo $this->tag->textField(array("grade","cols" => 25, "rows"=>4,"required" => 'required',"class"=>"form-control", "placeholder"=>"Grade")) ?>
              </div>
              <div class="form-group">
              <label for="stream" > Stream*</label>
              <?php echo $this->tag->textField(array("stream", "size" => 25 , "required" => 'required',"class"=>"form-control", "placeholder"=>"Stream")) ?>
              </div>
              <div id="submit_btn">
              <button type="submit" class="btn btn-default">Save</button>
              </div>
            </form>           
          </div>     
        </div>      
      </div>
    </div>