  <!--  bootstrap model pop up for add Experience-->
      <div class="modal fade" id="addExperience" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
             <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
             <h4 class="modal-title" id="exampleModalLabel">Add Experience </h4>
            </div>
            <div class="modal-body"> 
              <form method="post" name='form' id="formExperience" class="validateform" action="/eattendance/experience/create">
              <?php $this->flash->output(); ?> 
             
              <div class="form-group">
              <?php echo phalcon\Tag::hiddenField(array("user[iduser]","class"=>"form-control")); ?>
              </div>
              <div class="form-group">
              <label for="title" >Title*</label>
              <?php echo $this->tag->textField(array("title", "size" => 25 ,"required" => 'required',"class"=>"form-control", "placeholder"=>"Title")) ?>
              </div>
              <div class="form-group">
              <label for="description">Description</label>
              <?php echo $this->tag->textArea(array("description", "cols" => 25, "rows"=> 4,"class"=>"form-control", "placeholder"=>"Description")) ?>
              </div>
              <div class="form-group">
              <label for="from_date">From Date*</label>
              <?php echo $this->tag->textField(array("from_date", "size" => 25 ,"class"=>"form-control", "required" =>'required',"placeholder"=>"From Date","data-format"=>"yyyy/mm/dd","id"=>"fromcheck")) ?>
              </div>
              <div class="form-group">
              <label for="to_date">To Date*</label>
              <?php echo $this->tag->textField(array("to_date", "size" => 25 ,"required" =>'required',"class"=>"form-control", "placeholder"=>"To Date","data-format"=>"yyyy/mm/dd","id"=>"to")) ?>
              </div>
              <div class="form-group">
              <label for="company" >Company Name*</label>
              <?php echo $this->tag->textField(array("company", "size" => 25 ,"required" => 'required',"class"=>"form-control", "placeholder"=>"Company Name")) ?>
              </div>
              <div class="form-group">
              <label for="company_address">Company Address*</label>
              <?php echo $this->tag->textArea(array("company_address","cols" => 25, "rows"=>4,"required" => 'required',"class"=>"form-control", "placeholder"=>"Company Address")) ?>
              </div>
              <div class="form-group">
              <label for="company_ctc" >Company CTC(In Lakhs)*</label>
              <?php echo $this->tag->textField(array("company_ctc", "size" => 25 , "required" => 'required',"class"=>"form-control", "placeholder"=>"Company CTC")) ?>
              </div>
              <div id="submit_btn">
              <button type="submit" class="btn btn-default">Save</button>
              </div>
            
            </form>   
          </div>     
        </div>      
      </div>
    </div>