<?php $this->assets->outputCss('headercss') ?>
<?php $this->assets->outputCss('mainpagecss') ?>
<?php $this->assets->outputCss('datepickercss') ?>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
      <div class="col-md-4">
      <?php echo Phalcon\Tag::linkTo(array("document/index", "Back", "class"=>'btn btn-primary btn-large btn-success')); ?> 
      </div>
      <div class="col-md-4">
      <?php $this->flash->output(); ?>
      <?php echo $this->tag->form("document/save") ?>
        <div align="center">
            <h1>Edit document</h1>
        </div>
        <form>
          <div class="form-group">
          <?php echo phalcon\Tag::hiddenField(array("iddocument","class"=>"form-control" ));?>
          </div>
          <div class="form-group">
          <?php echo phalcon\Tag::hiddenField(array("iduser","class"=>"form-control"));?>
          </div>
          <div class="form-group">
          <label for="title" >Title*</label>
          <?php echo $this->tag->textField(array("title", "size" => 25 , 
          "required" => 'required',"class"=>"form-control", "placeholder"=>"Title"))?>
          </div>
          <div class="form-group">
          <label for="description"> Description</label>
          <?php echo $this->tag->textArea(array("description","cols" => 25, "rows" => 4,"class"=>"form-control","placeholder"=>"Description")) ?>
          </div>
          <div class="form-group">
          <label for="taken_date">Submit Date*</label>
          <?php echo $this->tag->textField(array("taken_date", "size" => 25 ,"required" => 'required',"class"=>"form-control", "placeholder"=>"Taken Date","data-format"=>"yyyy/mm/dd","id"=>"from")) ?>
          </div>
          <div class="form-group">
          <label for="given_date">Return Date*</label>
          <?php echo $this->tag->textField(array("given_date", "size" => 25 , "required" => 'required',"class"=>"form-control", "placeholder"=>"Given Date","data-format"=>"yyyy/mm/dd","id"=>"to")) ?>
          </div>
          <div id="submit_btn">
          <button type="submit" class="btn btn-default"> Submit </button>
          </div>
          </form>
        </div>
      </div>
    </div>          
</div>

<?php $this->assets->outputJs('footerjs') ?>
<?php $this->assets->outputJs('mainpagejs') ?>
<?php $this->assets->outputJs('datepickerjs') ?>

<script type="text/javascript">
 // When the document is ready
  jQuery(document).ready(function($) {  
      $('#from').datepicker({
              format: "yyyy/mm/dd"      
      });  
      $('#to').datepicker({
              format: "yyyy/mm/dd"      
      });        
  });
</script>   
