
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("document/new", "Create document")) ?>
</div>

<?php echo $this->tag->form(array("document/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search document</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="iddocument">Iddocument</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("iddocument", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="iduser">Iduser</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("iduser", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="title">Title</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("title", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="description">Description</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textArea(array("description", "cols" => 30, "rows" => 4)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="taken_date">Taken Of Date</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("taken_date", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="given_date">Given Of Date</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("given_date", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="created_by">Created Of By</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("created_by", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="updated_by">Updated Of By</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("updated_by", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="created_on">Created Of On</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("created_on", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="updated_on">Updated Of On</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("updated_on", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
