<?php $this->assets->outputCss('headercss') ?>
<?php $this->assets->outputCss('mainpagecss') ?>
<?php $this->assets->outputCss('datepickercss') ?>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
      	<div class="col-md-4">    
		  <?php echo Phalcon\Tag::linkTo(array("document/index", "Back", "class"=>'btn btn-primary btn-large btn-success')); ?>  	
		</div>
		<div class="col-md-4">
			<?php $this->flash->output(); ?>
			<div>
			 	<h1>Create document</h1>
			</div>
			<?php echo $this->tag->form("document/create") ?>				
			<form>
				<?php if($type == 1 || $type == 2) { ?>
    			<div class="form-group">
		    		<label for="iduser" > ID User </label>
        			<select name="iduser" class="form-control" >
			          <?php foreach($user as $users) { ?>
			          <option value="<?php echo $users->iduser; ?>">
			            <?php echo $users->iduser.'-'.$users->username; ?>
			          </option> 
			          <?php } ?>
			        </select>
	   		 	</div>
		   		<?php }else{ ?>
		   		<?php echo phalcon\Tag::hiddenField(array("iduser","class"=>"form-control" ));?>
		   		<?php } ?>
			    <div class="form-group">
			    <label for="title" >Title*</label>
			    <?php echo $this->tag->textField(array("title", "size" => 25 , 
			    "required" => 'required',"class"=>"form-control", "placeholder"=>"Title")) ?>
			    </div>
			    <div class="form-group">
			    <label for="description"> Description</label>
			    <?php echo $this->tag->textArea(array("description", "cols" => 25, "rows" => 4,"class"=>"form-control", "placeholder"=>"Description"))?>
			    </div>
			    <div class="form-group">
			    <label for="taken_date">Taken Date*</label>
			    <?php echo $this->tag->textField(array("taken_date", "size" => 25 ,"required" =>'required',"class"=>"form-control", "placeholder"=>"Taken Date","data-format"=>"yyyy/mm/dd","id"=>"from")) ?>
			    </div>
			    <div class="form-group">
			    <label for="given_date">Given Date*</label>
			    <?php echo $this->tag->textField(array("given_date", "size" => 25 , 
			    "required" => 'required',"class"=>"form-control", "placeholder"=>"Given Date","data-format"=>"yyyy/mm/dd","id"=>"to")) ?>
			    </div>
		        <div id="submit_btn">
		    	  <button type="submit" class="btn btn-default">Submit</button>
		        </div>
				</form>
		</div>
    </div>
  </div>
</div>
<?php $this->assets->outputJs('footerjs') ?>
<?php $this->assets->outputJs('mainpagejs') ?>
<?php $this->assets->outputJs('datepickerjs') ?>
<script type="text/javascript">
jQuery(document).ready(function($) {
    $('#from').datepicker({
        format: "yyyy/mm/dd"      
    });
    $('#to').datepicker({
        format: "yyyy/mm/dd"      
    }); 
 });
</script>
