
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("application/new", "Create application")) ?>
</div>

<?php echo $this->tag->form(array("application/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search application</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="idapplication">Idapplication</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("idapplication", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="iduser">Iduser</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("iduser", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="from_date">From Of Date</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("from_date", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="to_date">To Of Date</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("to_date", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="type">Type</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("type", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="title">Title</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("title", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="description">Description</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textArea(array("description", "cols" => 30, "rows" => 4)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="status">Status</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("status", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="created_on">Created Of On</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("created_on", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="updated_on">Updated Of On</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("updated_on", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
